[[redirects]]
  from = "/resume"
  to = "/Nikhil_Mehta.pdf"
  status = 200

[[redirects]]
  from = "/meeting/me"
  to = "https://meet.google.com/snd-nkbb-pnw"
  status = 307
  force = true

[[redirects]]
  from = "/meeting/book"
  to = "https://calendly.com/technikhil314/meet"
  force = true
  status = 307

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  headers = { X-Frame-Options = "DENY", X-XSS-Protection = "1; mode=block" }