[[redirects]]
  from = "/resume"
  to = "/Nikhil_Mehta.pdf"
  status = 200

[[redirects]]
  from = "/meet/me"
  to = "https://room.sh/go/meet-with-nikhil"
  status = 307
  force = true

[[redirects]]
  from = "/meet/book"
  to = "https://calendly.com/technikhil314/meet"
  force = true
  status = 307

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  headers = { X-Frame-Options = "DENY", X-XSS-Protection = "1; mode=block" }